# data_utils.py  — BAT-Mamba / PartialSpoof v1.2 edition
#
# Key facts about PartialSpoof v1.2:
#   - Audio: .wav files under {split}/con_wav/
#   - Audio list: {split}/{split}.lst
#   - CM protocol: protocols/PartialSpoof_LA_cm_protocols/PartialSpoof.LA.cm.{split}.trl.txt
#     format: SPEAKER_ID  AUDIO_NAME  -  SYSTEM_ID  KEY
#   - Segment labels: segment_labels/{split}_seglab_0.02.npy
#     format: dict { audio_name: np.array(['1','0',...]) }  '1'=bonafide, '0'=spoof
#   - Frame alignment: SR=16000, XLSR stride=320, cut=66800 -> 208 frames @ 20ms each

import numpy as np
import torch
from torch import Tensor
import soundfile as sf
import librosa
from torch.utils.data import Dataset
from RawBoost import process_Rawboost_feature
from utils import pad
from partialspoof_multiclass import (
    FRAME_DUR,
    NUM_FRAMES,
    CUT,
    SR,
    frame_labels_to_boundaries,
)
import os


def _load_audio(path, sr=16000):
    """Fast audio loader: tries soundfile first (10x faster), falls back to librosa."""
    try:
        X, sr_native = sf.read(path, dtype='float32', always_2d=False)
        if sr_native != sr:
            X = librosa.resample(X, orig_sr=sr_native, target_sr=sr)
    except Exception:
        X, _ = librosa.load(path, sr=sr)
    return X

# ============================================================
# Constants
# ============================================================
# Imported from partialspoof_multiclass to keep all 20ms/frame
# alignment logic centralized for binary and multiclass pipelines.


# ============================================================
# Load PartialSpoof .npy segment labels
# Returns: { audio_name: np.array of '0'/'1' strings }
#   '1' = bonafide,  '0' = spoof  (PartialSpoof convention)
# ============================================================
def load_seglab(npy_path):
    """Load a PartialSpoof segment-label .npy file.
    Returns dict: { audio_name (str): np.array(['1','0',...]) }
    """
    return np.load(npy_path, allow_pickle=True).item()


def load_frame_label_dict(npy_path):
    """Load converted frame labels stored as dict {utt_id: np.ndarray[int64]}.
    Accepts .npy dictionaries generated by convert_partialspoof_vad_labels.py.
    """
    data = np.load(npy_path, allow_pickle=True).item()
    normalized = {}
    for key, value in data.items():
        normalized[str(key)] = np.asarray(value, dtype=np.int64).reshape(-1)
    return normalized


# ============================================================
# Convert seglab array -> frame_labels + boundary_labels tensors
# seglab values: '1'=bonafide->0, '0'=spoof->1  (flip for our convention)
# ============================================================
def seglab_to_frame_labels(seglab_arr, num_frames=NUM_FRAMES):
    """
    Args:
        seglab_arr: np.array of strings ['1','0',...] from .npy file
        num_frames: int, target number of frames (default 208)
    Returns:
        frame_labels    : [num_frames] torch.long   0=bonafide, 1=spoof
        boundary_labels : [num_frames] torch.float32  1 at transition frames
    """
    # Truncate or pad seglab to num_frames
    arr = np.array(seglab_arr, dtype=np.int32)  # '1'->1 (bonafide), '0'->0 (spoof)
    # Flip: PartialSpoof '1'=bonafide->our 0, '0'=spoof->our 1
    arr = 1 - arr  # now: 0=bonafide, 1=spoof

    if len(arr) >= num_frames:
        arr = arr[:num_frames]
    else:
        # Pad with last label value (or 0 if empty)
        pad_val = int(arr[-1]) if len(arr) > 0 else 0
        arr = np.concatenate([arr, np.full(num_frames - len(arr), pad_val, dtype=np.int32)])

    frame_labels = torch.from_numpy(arr).long()   # [T]

    # Boundary: transition frames (diff != 0), mark the LATER frame
    diff = torch.abs(frame_labels[1:].float() - frame_labels[:-1].float())  # [T-1]
    boundary_labels = torch.zeros(num_frames, dtype=torch.float32)
    boundary_labels[1:] = diff

    return frame_labels, boundary_labels


def multiclass_frame_labels_to_tensors(frame_arr, num_frames=NUM_FRAMES):
    arr = np.asarray(frame_arr, dtype=np.int64).reshape(-1)
    if arr.size >= num_frames:
        arr = arr[:num_frames]
    else:
        pad_val = int(arr[-1]) if arr.size > 0 else 0
        arr = np.concatenate([arr, np.full(num_frames - arr.size, pad_val, dtype=np.int64)])
    frame_labels = torch.from_numpy(arr).long()
    boundary_labels = torch.from_numpy(frame_labels_to_boundaries(arr, num_frames=num_frames)).float()
    return frame_labels, boundary_labels


def build_segment_position_labels(frame_arr, num_frames=NUM_FRAMES, ignore_index=-100):
    arr = np.asarray(frame_arr, dtype=np.int64).reshape(-1)
    if arr.size >= num_frames:
        arr = arr[:num_frames]
    else:
        pad_val = int(arr[-1]) if arr.size > 0 else 0
        arr = np.concatenate([arr, np.full(num_frames - arr.size, pad_val, dtype=np.int64)])

    # 0=bona/ignore, 1=spoof_start, 2=spoof_middle, 3=spoof_end, 4=spoof_unit
    pos = np.full(num_frames, ignore_index, dtype=np.int64)
    spoof_mask = arr > 0
    idx = 0
    while idx < num_frames:
        if not spoof_mask[idx]:
            idx += 1
            continue
        start = idx
        while idx + 1 < num_frames and spoof_mask[idx + 1]:
            idx += 1
        end = idx
        seg_len = end - start + 1
        if seg_len == 1:
            pos[start] = 4
        else:
            pos[start] = 1
            pos[end] = 3
            if seg_len > 2:
                pos[start + 1:end] = 2
        idx += 1
    return torch.from_numpy(pos).long()


def apply_cross_segment_mix(waveform, frame_arr, donor_waveform, donor_frame_arr, mix_prob=0.0, min_frames=8, max_frames=64):
    if mix_prob <= 0 or np.random.rand() >= mix_prob:
        return waveform, frame_arr
    frame_arr = np.asarray(frame_arr, dtype=np.int64).reshape(-1).copy()
    donor_frame_arr = np.asarray(donor_frame_arr, dtype=np.int64).reshape(-1)
    if frame_arr.size == 0 or donor_frame_arr.size == 0:
        return waveform, frame_arr
    num_frames = min(frame_arr.size, donor_frame_arr.size, NUM_FRAMES)
    max_frames = max(min(max_frames, num_frames), 1)
    min_frames = max(min(min_frames, max_frames), 1)
    seg_len = np.random.randint(min_frames, max_frames + 1)
    start = np.random.randint(0, num_frames - seg_len + 1)
    end = start + seg_len

    mixed_waveform = waveform.clone()
    mixed_frame_arr = frame_arr.copy()
    mixed_frame_arr[start:end] = donor_frame_arr[start:end]

    samples_per_frame = int(round(SR * FRAME_DUR))
    sample_start = min(start * samples_per_frame, mixed_waveform.numel())
    sample_end = min(end * samples_per_frame, mixed_waveform.numel())
    if sample_end > sample_start:
        mixed_waveform[sample_start:sample_end] = donor_waveform[sample_start:sample_end]
    return mixed_waveform, mixed_frame_arr


# ============================================================
# Parse PartialSpoof CM protocol file
# Format: SPEAKER_ID  AUDIO_NAME  -  SYSTEM_ID  KEY
# Returns: (list_IDs, utt_label_dict)
# ============================================================
def parse_ps_protocol(protocol_file, is_eval=False):
    """
    Parse PartialSpoof CM protocol.
    Returns:
        list_IDs : list of audio names
        utt_labels: dict { audio_name: 0(bonafide)/1(spoof) }  (None if is_eval)
    """
    list_IDs = []
    utt_labels = {}
    with open(protocol_file, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 2:
                continue
            audio_name = parts[1]   # 2nd column: AUDIO_FILE_NAME
            list_IDs.append(audio_name)
            if not is_eval and len(parts) >= 5:
                key = parts[4]      # 5th column: KEY (bonafide/spoof)
                utt_labels[audio_name] = 0 if key == 'bonafide' else 1
    if is_eval:
        return list_IDs, None
    return list_IDs, utt_labels


# ============================================================
# PartialSpoof Training Dataset
# Returns: (waveform [66800], frame_labels [208] long, boundary_labels [208] float32)
# ============================================================
class Dataset_PartialSpoof_train(Dataset):
    """
    Args:
        list_IDs  : list of audio names (from parse_ps_protocol or .lst file)
        seglab    : dict from load_seglab(), { name: array }
        utt_labels: dict { audio_name: 0(bonafide)/1(spoof) }
        base_dir  : path to cached tensor dir, e.g. {split}/con_wav_pt_algo5/
        args      : argparse namespace (kept for backward compatibility)
        algo      : RawBoost algorithm index (kept for backward compatibility)
    """
    def __init__(self, list_IDs, seglab, utt_labels, base_dir, args, algo):
        self.list_IDs = list_IDs
        self.seglab = seglab
        self.utt_labels = utt_labels if utt_labels is not None else {}
        self.base_dir = self._resolve_pt_dir(base_dir, algo=algo, is_train=True)
        self.args = args
        self.algo = algo
        self.cut = CUT

    @staticmethod
    def _resolve_pt_dir(base_dir, algo, is_train):
        normalized = os.path.normpath(base_dir)
        if os.path.isdir(normalized) and normalized.endswith(f'con_wav_pt_algo{algo}'):
            return normalized
        if os.path.isdir(normalized) and normalized.endswith('con_wav_pt'):
            return normalized

        candidates = []
        if is_train:
            candidates.append(os.path.join(normalized, f'con_wav_pt_algo{algo}'))
            candidates.append(os.path.join(normalized, 'con_wav_pt'))
        else:
            candidates.append(os.path.join(normalized, 'con_wav_pt'))
            candidates.append(os.path.join(normalized, f'con_wav_pt_algo{algo}'))

        parent = os.path.dirname(normalized)
        if is_train:
            candidates.append(os.path.join(parent, f'con_wav_pt_algo{algo}'))
            candidates.append(os.path.join(parent, 'con_wav_pt'))
        else:
            candidates.append(os.path.join(parent, 'con_wav_pt'))
            candidates.append(os.path.join(parent, f'con_wav_pt_algo{algo}'))

        for candidate in candidates:
            if os.path.isdir(candidate):
                return candidate

        raise FileNotFoundError(
            'Cached tensor directory not found. Tried: {}. '
            'Please run preprocess_data.py first or pass the correct dataset root.'.format(candidates)
        )

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        pt_path = os.path.join(self.base_dir, utt_id + '.pt')
        waveform = torch.load(pt_path, map_location='cpu')
        if waveform.dim() != 1:
            waveform = waveform.reshape(-1)
        waveform = waveform[:self.cut].float().contiguous()
        if waveform.numel() != self.cut:
            raise ValueError(f'Cached tensor has wrong length for {utt_id}: {waveform.numel()} != {self.cut}')

        raw_lab = self.seglab.get(utt_id, np.ones(NUM_FRAMES, dtype=str))
        frame_labels, boundary_labels = seglab_to_frame_labels(
            raw_lab, num_frames=NUM_FRAMES
        )
        utt_label = torch.tensor(self.utt_labels.get(utt_id, int(frame_labels.max().item() > 0)), dtype=torch.long)

        return waveform, frame_labels, boundary_labels, utt_label


# ============================================================
# PartialSpoof Eval Dataset
# Returns: (waveform [66800], frame_labels [208], boundary_labels [208], utt_label, utt_id)
# ============================================================
class Dataset_PartialSpoof_eval(Dataset):
    def __init__(self, list_IDs, seglab, utt_labels, base_dir, skip_missing=False):
        self.list_IDs = list_IDs
        self.seglab = seglab
        self.utt_labels = utt_labels if utt_labels is not None else {}
        self.base_dir = Dataset_PartialSpoof_train._resolve_pt_dir(base_dir, algo=0, is_train=False)
        self.wav_base_dir = os.path.join(os.path.dirname(self.base_dir), 'con_wav')
        self.cut = CUT
        self.skip_missing = skip_missing

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        pt_path = os.path.join(self.base_dir, utt_id + '.pt')
        if os.path.exists(pt_path):
            waveform = torch.load(pt_path, map_location='cpu')
        else:
            wav_path = os.path.join(self.wav_base_dir, utt_id + '.wav')
            if not os.path.exists(wav_path):
                if self.skip_missing:
                    return None
                raise FileNotFoundError(f'Missing both cached tensor and wav for {utt_id}: {pt_path} | {wav_path}')
            x = _load_audio(wav_path, sr=SR)
            x_pad = pad(np.asarray(x, dtype=np.float32), self.cut)
            waveform = torch.tensor(x_pad, dtype=torch.float32)
            try:
                os.makedirs(self.base_dir, exist_ok=True)
                torch.save(waveform.contiguous(), pt_path)
            except Exception:
                pass
        if waveform.dim() != 1:
            waveform = waveform.reshape(-1)
        waveform = waveform[:self.cut].float().contiguous()
        if waveform.numel() != self.cut:
            raise ValueError(f'Cached tensor has wrong length for {utt_id}: {waveform.numel()} != {self.cut}')

        raw_lab = self.seglab.get(utt_id, np.ones(NUM_FRAMES, dtype=str))
        frame_labels, boundary_labels = seglab_to_frame_labels(
            raw_lab, num_frames=NUM_FRAMES
        )
        utt_label = torch.tensor(self.utt_labels.get(utt_id, int(frame_labels.max().item() > 0)), dtype=torch.long)
        return waveform, frame_labels, boundary_labels, utt_label, utt_id


class Dataset_PartialSpoof_multiclass_train(Dataset):
    def __init__(self, list_IDs, frame_label_dict, utt_labels, base_dir, args, algo):
        self.list_IDs = list_IDs
        self.frame_label_dict = frame_label_dict
        self.utt_labels = utt_labels if utt_labels is not None else {}
        self.base_dir = Dataset_PartialSpoof_train._resolve_pt_dir(base_dir, algo=algo, is_train=True)
        self.args = args
        self.algo = algo
        self.cut = CUT

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        pt_path = os.path.join(self.base_dir, utt_id + '.pt')
        waveform = torch.load(pt_path, map_location='cpu')
        if waveform.dim() != 1:
            waveform = waveform.reshape(-1)
        waveform = waveform[:self.cut].float().contiguous()
        if waveform.numel() != self.cut:
            raise ValueError(f'Cached tensor has wrong length for {utt_id}: {waveform.numel()} != {self.cut}')

        raw_lab = self.frame_label_dict.get(utt_id, np.zeros(NUM_FRAMES, dtype=np.int64))
        if getattr(self.args, 'cross_segment_mix_prob', 0.0) > 0 and len(self.list_IDs) > 1:
            donor_index = np.random.randint(0, len(self.list_IDs) - 1)
            if donor_index >= index:
                donor_index += 1
            donor_id = self.list_IDs[donor_index]
            donor_pt_path = os.path.join(self.base_dir, donor_id + '.pt')
            donor_waveform = torch.load(donor_pt_path, map_location='cpu')
            if donor_waveform.dim() != 1:
                donor_waveform = donor_waveform.reshape(-1)
            donor_waveform = donor_waveform[:self.cut].float().contiguous()
            donor_raw_lab = self.frame_label_dict.get(donor_id, np.zeros(NUM_FRAMES, dtype=np.int64))
            waveform, raw_lab = apply_cross_segment_mix(
                waveform,
                raw_lab,
                donor_waveform,
                donor_raw_lab,
                mix_prob=getattr(self.args, 'cross_segment_mix_prob', 0.0),
                min_frames=getattr(self.args, 'cross_segment_mix_min_frames', 8),
                max_frames=getattr(self.args, 'cross_segment_mix_max_frames', 64),
            )
        frame_labels, boundary_labels = multiclass_frame_labels_to_tensors(raw_lab, num_frames=NUM_FRAMES)
        segment_pos_labels = build_segment_position_labels(raw_lab, num_frames=NUM_FRAMES)
        utt_label = torch.tensor(self.utt_labels.get(utt_id, int(frame_labels.max().item() > 0)), dtype=torch.long)
        return waveform, frame_labels, boundary_labels, utt_label, segment_pos_labels


class Dataset_PartialSpoof_multiclass_eval(Dataset):
    def __init__(self, list_IDs, frame_label_dict, utt_labels, base_dir, skip_missing=False):
        self.list_IDs = list_IDs
        self.frame_label_dict = frame_label_dict
        self.utt_labels = utt_labels if utt_labels is not None else {}
        self.base_dir = Dataset_PartialSpoof_train._resolve_pt_dir(base_dir, algo=0, is_train=False)
        self.wav_base_dir = os.path.join(os.path.dirname(self.base_dir), 'con_wav')
        self.cut = CUT
        self.skip_missing = skip_missing

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        pt_path = os.path.join(self.base_dir, utt_id + '.pt')
        if os.path.exists(pt_path):
            waveform = torch.load(pt_path, map_location='cpu')
        else:
            wav_path = os.path.join(self.wav_base_dir, utt_id + '.wav')
            if not os.path.exists(wav_path):
                if self.skip_missing:
                    return None
                raise FileNotFoundError(f'Missing both cached tensor and wav for {utt_id}: {pt_path} | {wav_path}')
            x = _load_audio(wav_path, sr=SR)
            x_pad = pad(np.asarray(x, dtype=np.float32), self.cut)
            waveform = torch.tensor(x_pad, dtype=torch.float32)
            try:
                os.makedirs(self.base_dir, exist_ok=True)
                torch.save(waveform.contiguous(), pt_path)
            except Exception:
                pass
        if waveform.dim() != 1:
            waveform = waveform.reshape(-1)
        waveform = waveform[:self.cut].float().contiguous()
        if waveform.numel() != self.cut:
            raise ValueError(f'Cached tensor has wrong length for {utt_id}: {waveform.numel()} != {self.cut}')

        raw_lab = self.frame_label_dict.get(utt_id, np.zeros(NUM_FRAMES, dtype=np.int64))
        frame_labels, boundary_labels = multiclass_frame_labels_to_tensors(raw_lab, num_frames=NUM_FRAMES)
        utt_label = torch.tensor(self.utt_labels.get(utt_id, int(frame_labels.max().item() > 0)), dtype=torch.long)
        return waveform, frame_labels, boundary_labels, utt_label, utt_id


# ============================================================
# Backward-compat: original ASVspoof2019 sentence-level Datasets
# ============================================================
def genSpoof_list(dir_meta, is_train=False, is_eval=False):
    d_meta = {}
    file_list = []
    with open(dir_meta, 'r') as f:
        l_meta = f.readlines()
    if is_train:
        for line in l_meta:
            _, key, _, _, label = line.strip().split()
            file_list.append(key)
            d_meta[key] = 1 if label == 'bonafide' else 0
        return d_meta, file_list
    elif is_eval:
        for line in l_meta:
            key = line.strip()
            file_list.append(key)
        return file_list
    else:
        for line in l_meta:
            _, key, _, _, label = line.strip().split()
            file_list.append(key)
            d_meta[key] = 1 if label == 'bonafide' else 0
        return d_meta, file_list


class Dataset_train(Dataset):
    """Original sentence-level dataset (ASVspoof2019 LA)."""
    def __init__(self, args, list_IDs, labels, base_dir, algo):
        self.list_IDs = list_IDs
        self.labels   = labels
        self.base_dir = base_dir
        self.algo     = algo
        self.args     = args
        self.cut      = CUT

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        X, fs = librosa.load(
            os.path.join(self.base_dir, 'flac', utt_id + '.flac'), sr=SR)
        Y = process_Rawboost_feature(X, fs, self.args, self.algo)
        X_pad = pad(Y, self.cut)
        x_inp = Tensor(X_pad)
        target = self.labels[utt_id]
        return x_inp, target


class Dataset_eval(Dataset):
    """Original sentence-level eval dataset (ASVspoof2019 LA)."""
    def __init__(self, list_IDs, base_dir, track):
        self.list_IDs = list_IDs
        self.base_dir = base_dir
        self.cut      = CUT
        self.track    = track

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        X, _ = librosa.load(
            os.path.join(self.base_dir, 'flac', utt_id + '.flac'), sr=SR)
        X_pad = pad(X, self.cut)
        return Tensor(X_pad), utt_id


class Dataset_in_the_wild_eval(Dataset):
    def __init__(self, list_IDs, base_dir):
        self.list_IDs = list_IDs
        self.base_dir = base_dir
        self.cut      = 64600

    def __len__(self):
        return len(self.list_IDs)

    def __getitem__(self, index):
        utt_id = self.list_IDs[index]
        X, _ = librosa.load(self.base_dir + utt_id, sr=SR)
        X_pad = pad(X, self.cut)
        return Tensor(X_pad), utt_id
